# Generated by Django 5.0.6 on 2024-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
