# Generated by Django 5.0.6 on 2024-09-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0003_remove_variation_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='defult',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
